name: Build

on:
  push:
  pull_request:

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-24.04]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          path: SolarLoRaBox_Firmware

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.11

      - name: Setup Zephyr project
        uses: zephyrproject-rtos/action-zephyr-setup@v1
        with:
          app-path: SolarLoRaBox_Firmware
          toolchains: arm-zephyr-eabi

      - name: Build all firmware apps
        working-directory: SolarLoRaBox_Firmware
        shell: bash
        run: |
          if [ "${{ runner.os }}" = "Windows" ]; then
            EXTRA_TWISTER_FLAGS="--short-build-path -O/tmp/twister-out"
          fi

          # Find all application directories under "apps"
          for app_dir in apps/*; do
            if [ -d "$app_dir" ]; then
              echo "Building application in $app_dir"
              west twister -T "$app_dir" -v --inline-logs --integration $EXTRA_TWISTER_FLAGS
            fi
          done
